input CreateUserInput {
	name: String!
	email: String!
	password: String!
}

input CreateTodoInput {
	todo: String!
	deadline: DateTime!
}

input ResetPasswordInput {
	email: String
	token: String
	password: String
}
